# Generated by Django 4.2.1 on 2023-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=128, verbose_name='이메일')),
                ('number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('body', models.TextField(default='', verbose_name='내용')),
            ],
        ),
    ]
